version: '3.8'

services:
  server-api:
    hostname: demo-server-api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - NODE_ENV=production
    command: ['node', 'server.mjs']

networks:
  default:
    name: multi-compose-net
    external: true
